@MinimalApi_HostAddress = http://localhost:5077

POST {{MinimalApi_HostAddress}}/order/
Content-Type: application/json

{
    "customerName": "John Doe",
    "totalPrice": 100
}

###

@OrderId = 048C0W7DMWYPA
GET {{MinimalApi_HostAddress}}/order/{{OrderId}}
Accept: application/json

###

POST {{MinimalApi_HostAddress}}/product/
Content-Type: application/json

{
    "Name": "Apple Macbook"
}

###

@ProductId= 07047XF6Q8YPA
GET {{MinimalApi_HostAddress}}/product/{{ProductId}}
Accept: application/json

###
